### ISSUE TITLE
naturalWidth of SVG returns 0 on IE11

### ISSUE THREAD

**Issue by sectsect** [fregante/image-promise#19]
Thanks for useful package.

`naturalWidth` of SVG returns `0` on IE11, and I get an error.

Related: https://stackoverflow.com/questions/22822921/how-can-i-get-width-and-height-of-svg-on-image-load-in-ie-11

**Comment by fregante** [comment]
This appears to be the same as https://github.com/fregante/image-promise/issues/10

IE11 isn't fully supported. A fix would complicate things considerably
