### ISSUE TITLE
SVGs with set dimensions return too early

### ISSUE THREAD

**Issue by aldebout** [fregante/image-promise#23]
When trying to load an svg and explicitely setting its height and weight, the promise returns too early (`img.complete === false`)

```js
const img = await loadImages('***.svg', {
    height: `100px`,
    width: `100px`,
  });
```

I patched it by changing the condition to `if (image.naturalWidth && image.complete)`, is this something that we should consider? Do you want me to open a pr when I have the time?

**Comment by fregante** [comment]
Good point. The conditions should be shuffled as:

```
if not complete
  add listeners
else if naturalWidth
  it’s loaded
else
  it’s failed

**Comment by fisker** [comment]
Consider use `HTMLImageElement.decode()`(https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decode)?

**Comment by fregante** [comment]
Yes! I'd accept a PR for that.

Sorry I didn't see this earlier

**Comment by fregante** [comment]
Just use .decode(). I'm deprecating this package.

```js
const img = new Image('***.svg');
img.height = `100px`;
img.width = `100px`;
await img.decode();
```

**Comment by fisker** [comment]
`Image` doesn't accept src

```js
const img = new Image(100, 100);
img.src = '***.svg';
await img.decode();
```
